name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'production'
      version:
        description: 'Version of the app to deploy'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} with version ${{ github.event.inputs.version }}"
